name: Sync to Gitea

on:
  push:
    branches: [ main ]

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Push to Gitea
        env:
          GITEA_REPO: https://gitea.com/CJKmkp/ICC-CE.git
          GITEA_TOKEN: 2cd2e3be72be915d738043b44ec53024ac87271c
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          
          # 推送代码到 Gitea
          git push -u gitea --all
          git push -u gitea --tags
